FROM debian:buster-slim

LABEL maintainer="calvintam236"
LABEL description="geth in Docker. Full node. Supports CPU mining."

WORKDIR /tmp/

ADD \
https://gethstore.blob.core.windows.net/builds/geth-linux-arm6-1.10.17-25c9b49f.tar.gz \
.

RUN \
tar -xvf geth-linux-arm6-1.10.17-25c9b49f.tar.gz \
&& mv geth-linux-arm6-1.10.17-25c9b49f/geth /usr/local/bin/ \
&& chmod +x /usr/local/bin/geth \
&& rm -r *

ENTRYPOINT ["geth"]
CMD ["--help"]
